### ISSUE TITLE
Assign Francisco Juarez to HeardLibrary GitHub Team

### ISSUE THREAD

**Issue by juarezfd** [HeardLibrary/digital-scholarship#11]

**Comment by baskaufs** [comment]
Jodie's added him as "triage" to the repo but not the HeardLibrary team. We'll see if that works.

**Comment by baskaufs** [comment]
@juarezfd Do the options for assignees and projects now show up for you on the right? If so, I think this issue is done and you can close it.

**Comment by juarezfd** [comment]
Hello,

The option for assignees appeared, so I closed the card.
Thanks for taking care of this, Jodie.

-Francisco Juarez
