### ISSUE TITLE
Set a date for two lessons and rocket launch

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/digital-scholarship#12]
We can hold off on this until we hear back from Greg #10

**Comment by baskaufs** [comment]
Possible slots at https://whenisgood.net/2hq4jiy

**Comment by baskaufs** [comment]
Emailed scheduler link to Greg 2021-01-18

**Comment by juarezfd** [comment]
Francisco Juarez summited response to "whenisgood" poll @ 2022-01-18 15:006 

Francisco checked the availability of the MapRoom/SeminarRoom on 2021-01-18, and it is available every day except Fridays at 15:30-17:00 due to an Organic LA meeting.

**Comment by baskaufs** [comment]
It looks like the Friday 10 AM slot that we talked about would work. I'll double check with Greg and then we can schedule the room.
![schedule](https://user-images.githubusercontent.com/5765781/150031625-90d091dc-86fc-4d38-83ee-d2197e8b7cee.png)

**Comment by juarezfd** [comment]
Spoke with Greg 
Francisco scheduled dates for
April 1, 8, 15
Friday @ 1 pm 
in the SEL Seminar Room

**Comment by baskaufs** [comment]
Outlook calendar event created for those dates and time
