### ISSUE TITLE
Order parts

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/digital-scholarship#8]
- [x] Decide what parts we need.
- [x] Look up ordering information. Look up in [Adafruit catalog](https://www.adafruit.com/)
- [x] Get *Machelle* to order them

**Comment by baskaufs** [comment]
Note: Adafruit seems to have a price break on some items at >10. **Note:** If items are out of stock, put in email address to be notified. They do not backorder. It may be necessary to do two orders since one thing may go out of stock again by the time the other comes in. Total cost should be $458.05 if I did the math right.

| quantity_requested | price | description | URL/product ID | quantity_arrived
| -------- | ---- | ------------ | ---------------- | -------- |
| 10 | $8.96 | Adafruit QT Py RP2050 | https://www.adafruit.com/product/4900 | 10 |
| 10 | 5.36 | Adafruit VCNL4040 Proximity and Lux Sensor - STEMMA QT / Qwiic | https://www.adafruit.com/product/4161 | 10 |
| 35 | 0.95 | STEMMA QT / Qwiic JST SH 4-Pin Cable - 50mm Long | https://www.adafruit.com/product/4399 | 35 |
| 10 | 9.95 | USB C to USB C Cable - USB 3.1 Gen 4 with E-Mark - 1 meter long | https://www.adafruit.com/product/4199 | 10 |
| 10 | 4.46 | USB Type A to Type C Cable - approx 1 meter / 3 ft long | https://www.adafruit.com/product/4474 | 10 |
| 2 | 14.95 |  Adafruit LSM6DS33 + LIS3MDL - 9 DoF IMU with Accel / Gyro / Mag - STEMMA QT Qwiic |https://www.adafruit.com/product/4485 | 0 |
| 2 | 9.95 |  Adafruit BMP280 I2C or SPI Barometric Pressure & Altitude Sensor - STEMMA QT | https://www.adafruit.com/product/2651 | 2 |
| 2 | 13.95 | Adafruit VL6180X Time of Flight Distance Ranging Sensor (VL6180) - STEMMA QT | https://www.adafruit.com/product/3316 | 2 |
| 2 | 9.95 | Adafruit HTS221 - Temperature & Humidity Sensor Breakout Board - STEMMA QT / Qwiic |  https://www.adafruit.com/product/4535 | 0 |
| 2 | 19.95 | Monochrome 1.3" 128x64 OLED graphic display - STEMMA QT / Qwiic | https://www.adafruit.com/product/938 | 2 |

**Comment by baskaufs** [comment]
Emailed Machelle 2021-01-13 about ordering

**Comment by juarezfd** [comment]
Francisco messaged Machelle asking about the eta of the parts

"Hi. They are supposed to be there today, but I won't be in the office until later this week.
Once I am in the office I can verify that it has been delivered. I will let you both know." - Machelle 20220118
