### ISSUE TITLE
Check on availability of map room and reserve

### ISSUE THREAD

**Issue by baskaufs** [HeardLibrary/digital-scholarship#9]
Machelle knows how to do it.

Probably around the last week of March and first week of April.

**Comment by juarezfd** [comment]
"Typically you just make a room reservation, but they are turned off until after we open back up on the 24th. I think as long as it is after the 24th you should be able to make one.  [Library Room Reservation](https://www.library.vanderbilt.edu/services/studyrooms.php)

Just scroll down to Science and choose that room - FYI the seminar room is now its title. And it is number 3211" - Machelle 20220112

**Comment by juarezfd** [comment]
Francisco booked/reserved
April 1, 8, 15
at 1 pm
SEL Seminar Room
- 20220124
